<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-toolbar blog-toolbar-top">
   <?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
<?php 
$_hpImages = Mage::helper('blog/images');
$width  = 776;
$height = 555;
?>
<div class="row">
<?php foreach ($posts as $post): ?>
    <div class="postWrapper col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="blog-poss">
            <div class="blog-image al-style-2 image-container">
               <a class="blog-img-none" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'">' : ''; ?>
               </a>
                <div class="post-date">
                  <?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
				  <i class="fa fa-calendar" aria-hidden="true"></i><?php echo date("d M Y", $date) ?>
				</div>
            </div>
            <div class="blog-content-inner">
            	<div class="postTitle">
				    <h2>
				   <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
				    </h2>
			    </div>
			    <div class="blog-head post-date clearfix">
					<div class="postDetails">
		            	<span class="lnr lnr-clock"></span><span><?php echo $post->getCreatedTime(); ?></span>
		            	<?php $postCats = $post->getCats(); ?>
						<?php if (!empty($postCats)): ?>
							<?php //echo Mage::helper('blog')->__('Posted in'); ?>
							<?php foreach ($postCats as $data): ?>
								<!--<a href="<?php //echo $data['url']; ?>"><?php //echo $data['title']; ?></a-->
							<?php endforeach; ?>
						<?php else: ?>
							<?php echo Mage::helper('blog')->__('Posted'); ?>
						<?php endif; ?><span class="posted"><?php echo $this->__("Post By:"); ?></span> <span class="user"><?php echo $post->getUser(); ?></span>
						<?php if ($this->getCommentsEnabled()): ?>
							<?php echo $post->getCommentCount(); ?> <a class="comment" href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a>
						<?php endif; ?>
		            </div>
	            </div>
			    <div class="postContent">
			    <?php echo $post->getPostContent(); ?>
			    </div>
				<?php //echo $this->getTagsHtml($post) ?>
				<?php echo $this->getBookmarkHtml($post) ?>
            </div>
		</div>
    </div>
<?php endforeach; ?>
</div>
<div class="blog-toolbar blog-toolbar-bottom clearfix">
<?php echo $this->getChildHtml('blog_comments_toolbar'); ?>
</div>
