<?php
if(!Mage::helper('blog')->isEnabled()) return;
$_hpImages = Mage::helper('blog/images');
$rows 	= $this->getRow() ? $this->getRow() : 1;
$width  = $this->getData('widthImages') ? $this->getData('widthImages') : 135;
$height = $this->getData('heightImages') ? $this->getData('heightImages') : 135;
?>

<?php if ($posts = $this->getRecent()):  $i = 1;?>
<?php $selector = $this->generateRandomString(); //md5(rand()); //rand(0,666666); ?>
<?php 
	$margin  = (int) $this->getData('marginColumn');
	$slide   = json_encode($this->setFlexiselArray());
	$options = json_encode($this->getItemsDevice());
?>
	<div class="<?php echo $selector?>">
		<div class="blogtabs block-title-tabs">
			<h3 class="item active loaded section-title title_left" data-type ="blog"><?php echo $this->__($this->getTitle()) ?></h3>
			<div class="desc-blog"><?php echo $this->__('Read Our Blog') ;?></div>
		</div>
		<div class="content-blog content-products" data-margin="<?php echo $margin ?>" data-slider='<?php echo $slide ?>' data-options='<?php echo $options; ?>'>
			<div class="mc-blog">
				<ul class="flexisel-content">
					<?php foreach ($posts as $post): ?>
						<li class="item">
						   <div class="postcontent">
								<div class="blog_short_text clearfix">
								    <div class="blog-image al-style-2 image-container hover-effect">
										<a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'" alt="imgBlog"/>' : ''; ?>
										</a>
									</div>
								    <div class="blog_text">
								        <div class="content-inner">
										    <div class="post-date">
											  <?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
											  <?php echo date("d M Y", $date) ?>
											</div>
								        	<a href="<?php echo $post->getAddress(); ?>" ><?php echo '<span class="title">'.$post->getTitle().'</span>' ?></a>
										    <div class="contentime">
								            <span class="lnr lnr-clock"></span><span class="createdtime"><?php echo $post->getCreatedTime(); ?></span>
								            <span class="posted"><?php echo $this->__("By:"); ?></span> <span class="poster user"><?php echo $post->getUser(); ?></span>
								            </div>

										    <div class="shortcontent-text">
												<p class="short-text"><?php echo $this->getContentBlogSidebar(strip_tags($post->getShortContent()),140);?>...
												</p>
											</div>
											<a class="read-more-blog" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read more') ;?>
											</a>
								        </div>
									</div>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>			
		</div>
	</div>
<?php endif ?>
<script type="text/javascript">
jQuery(document).ready(function () {
	jQuery(".<?php echo $selector?>").magicproduct({
		tabs  : '.blogtabs',
		product  : '.content-blog',
	});
});
</script>
